export enum emitterEnum {
    CAN_SHOW_QUESTION = "canShowQuestion",
}

export enum routerEnum {
    HOME = "/home",
    FORM = "/form",
    FORM_ANSWER = "/form-answer",
    QUESTION = "/question",
    INITIAL = "/",
    PLANEJA = "/planeja",
    PLANEJA_PRATICO = "/planeja-pratico",
    DATACEO = "/ceo",
    DATAAPS = "/aps",
    RESETPWD = "/recuperar",
    DATA = "/data",
    PROJECT = "/project",
    TEAM = "/team",
    ARTICLES = "/articles",
    CONTACTUS = "/contactus",
    FAQ = "/faq",
    CEO = "/ceodata",
    APS = "/apsdata",
    USER = "/userdata",
    TCLE = "/tcle",
    DIRECTION = "/direction",
    DATAFORM = "/dataform",
    DASHBOARD = "/dashboard",
    DASHBOARD_VIGIA = "/dashboard/vigia",
    DASHBOARD_CEO = "/dashboard/ceo",
    ADMIN = "/admin",
}

export enum titleEnumPtBr {
    "/ceodata" = "Dados CEO",
    "/apsdata" = "Dados APS",
    "/userdata" = "Dados usuario",
    "/faq" = "F.A.Q",
    "/contactus" = "Contato",
    "/articles" = "Artigos",
    "/team" = "Quem somos?",
    "/project" = "Projeto",
    "/" = "Início",
    "/home" = "Início",
    "/tcle" = "TCLE",
    "/direction" = "Endereço",
    "/form" = "Formularios",
    // "/question" = "Questionario inicial",
    "/planeja" = "PlanejaSD Teorico",
    "/planeja-pratico" = "PlanejaSD Pratico",
    "/ceo" = "Dados CEO",
    "/aps" = "Dados APS",
    "/data" = "Exportar dados",
    "/dashboard" = "Central de Dashboards",
    "/dashboard/vigia" = "Dashboard Vigia SD",
    "/dashboard/ceo" = "Dashboard CEO",
    "/admin" = "Painel Admin",
}

export enum localStorageKeyEnum {
    TOKEN = "token",
    TYPE_ID = "typeId",
    USER_ID = "userId",
}

export enum loginTypeEnum {
    CPF = "cpf",
    DDI_DDD_CELLPHONE = "ddi-ddd-cellphone",
    EMAIL = "email",
    USERNAME = "username",
    ALL = "all",
}

export enum containerBodyTypeEnum {
    MAIN = "main",
    ABOUT_US = "about-us",
    CONTACT_US = "contact-us",
    COLLECTION = "collection",
    COURSE = "course",
    REFERENCE = "reference",
    QUESTIONS = "questions",
    FAQ = "faq",
    TCLE = "tcle",
    DIRECTION = "direction",
    INFORMES = "informes",
    WHAT_IS = "what-is",
    USER_DATA = "user-data",
    CEO_DATA = "ceo-data",
    APS_DATA = "aps-data",
}
